//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiringStaff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int Код_документа { get; set; }
        public int Код_сотрудника { get; set; }
        public int Серия_паспорта { get; set; }
        public int Номер_паспорта { get; set; }
        public long ИНН { get; set; }
        public long СНИЛС { get; set; }
        public long Номер_медицинского_полюса { get; set; }
        public byte[] Фотография { get; set; }
        public Nullable<long> Номер_трудового_договора { get; set; }
        public Nullable<int> Срок_действия_договора { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
