//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiringStaff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Классы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Классы()
        {
            this.Преподоваемые_часы = new HashSet<Преподоваемые_часы>();
        }
    
        public int Код_класса { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Код_классного_руководителя { get; set; }
        public Nullable<int> Код_классного_кабинета { get; set; }
        public int Количество_учеников { get; set; }
    
        public virtual Помещение Помещение { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Преподоваемые_часы> Преподоваемые_часы { get; set; }
    }
}
